# Lesson 2: Importing & Exploring Data

In this lesson, we'll learn to pull data into our Python environment and run some of the first diagnostics we'll need to understand our data.

Why don't you kick us off by importing our two most important data analytic tools into our Jupyter notebook: Pandas and Numpy?

## Exercise 1
Import Pandas and NumPy into your Jupyter Notebook and assign the standard aliases to them.

In [1]:
import pandas as pd
import numpy as np

## Exercise 2

Now let's go straight into importing data into our Python environment! Check out DC's Open Data Portal at opendata.dc.gov.

From here, we'll import data into our Python environment in two different ways. First, let's try downloading the data from the website and then pulling it into this notebook. 

Find the City Service Requests for 2016 in DC's Open Data Portal and download the spreadsheet (.csv file) to your computer.

This is a data set containing requests for service through DC's 311 system. People can enter these requests by calling 311, texting DC-311 (32-311), using the 311 app, or visiting the city's online 311 portal. 

Now let's try pulling the data into our Python environment using Pandas. 


Pull the .csv file into your Python environment using Pandas and assign it to an object called 'df'.

In [2]:
pd.read_csv('City_Service_Requests_in_2016.csv')

FileNotFoundError: File b'City_Service_Requests_in_2016.csv' does not exist

What happened? You may have received an error like this: "OSError: File b'City_Service_Requests_in_2016.csv' does not exist"

This means that the .csv file is not in the directory your notebook is calling from (which is, in fact, the directory the notebook is in). To find out which directory your notebook is calling from, import the os package and get the current working directory.

## Exercise 3

Import the os package and get the current working directory.

In [3]:
%ls 
#line magic is more I-Pythonic

 Volume in drive C has no label.
 Volume Serial Number is BA59-3588

 Directory of C:\Users\CDL\Documents\My python learning\assignment-02-master

09/14/2017  12:51 AM    <DIR>          .
09/14/2017  12:51 AM    <DIR>          ..
09/13/2017  12:05 AM    <DIR>          .ipynb_checkpoints
09/14/2017  12:51 AM           203,006 assignment-02.ipynb
09/12/2017  01:01 AM           253,802 assignment-02-Exploratory.ipynb
09/13/2017  10:36 PM    <DIR>          data
09/09/2017  11:45 AM               842 README.md
               3 File(s)        457,650 bytes
               4 Dir(s)  306,130,620,416 bytes free

Ok, now that we know what the current working directory is, we must either change the working directory or move the file into the current working directory. I'll let you decide which you want to do, but this is how you change the working directory.

In [4]:
os.chdir('C:\\Users\\peter.casey\\Downloads') 
## There's this weird thing in Python where you have to use double slashes when specifying working directories.
## If you have trouble getting a file from a directory you know it's in, this is a common error.

#

NameError: name 'os' is not defined

Now you should be able to pull the data into your Jupyter Notebook. Try it again.

In [7]:
df = pd.read_csv("https://opendata.arcgis.com/datasets/0e4b7d3a83b94a178b3d1f015db901ee_7.csv")

In [1]:
mkdir data

In [8]:
df.to_csv('data/serv_16.csv') #more ipythonic to mkdir and save to data folder

We can also pull the .csv file directly from the Open Data Portal by using the link.

In [9]:
## I'm commenting this out because it takes a while to pull the data into the environment because it's a large file
#df = pd.read_csv('https://opendata.arcgis.com/datasets/0e4b7d3a83b94a178b3d1f015db901ee_7.csv')

Great! You have the data! 

One of the first things we'd like to know when we're dealing with a data set is its shape; that is the number of rows and columns it has.

In [10]:
df.shape

(302985, 30)

This data has 302,925 rows and 30 columns. Generally speaking, rows are our "observations" or "samples", while columns are our "variables" or "features". 

Now try getting JUST the number of rows.

In [11]:
df.shape[0]

302985

When you have an item like this with multiple elements, you can often call the elements by their number. In Python, we always start counting elements with the number '0', so that the first element is always element '0'. 

## Exercise 4
Now try getting the number of columns yourself.

In [12]:
df.shape[1]

30

The next thing we may want to do is actually LOOK at the data. But you probably don't want to print out all 300,000 rows of data in your notebook! (In reality, Pandas won't do that. Instead, it will show you a subset of the rows.)

But to have greater control we can use the head command.

In [13]:
df.head()

,X,Y,OBJECTID,SERVICECODE,SERVICECODEDESCRIPTION,SERVICETYPECODEDESCRIPTION,ORGANIZATIONACRONYM,SERVICECALLCOUNT,ADDDATE,RESOLUTIONDATE,...,XCOORD,YCOORD,LATITUDE,LONGITUDE,CITY,STATE,ZIPCODE,MARADDRESSREPOSITORYID,WARD,DETAILS
0,-77.068472,38.959221,928367,EMNPV,Emergency No-Parking Verification,PEMA- Parking Enforcement Management Administr...,DPW,1,2016-01-04T16:45:21.000Z,2016-01-04T21:13:04.000Z,...,394065.60,143480.700000,38.959214,-77.068470,WASHINGTON,DC,20015.0,262895.0,3.0,NaN
1,-77.028858,38.903745,947826,S0276,Parking Meter Repair,Transportation Operations Administration,DDOT,1,2016-05-02T11:43:31.000Z,2016-05-03T01:38:10.000Z,...,397497.09,137320.600003,38.903738,-77.028856,WASHINGTON,DC,20005.0,812754.0,2.0,Need More Information
2,-77.019418,38.941567,947827,S0361,Sidewalk Repair,Toa-Street & Bridge Maintenance,DDOT,1,2016-05-02T11:47:49.000Z,NaN,...,398316.79,141518.950000,38.941560,-77.019416,WASHINGTON,DC,20011.0,247564.0,4.0,NaN
3,-77.014655,38.906236,947828,PRUNING,Tree Pruning,Urban Forrestry,DDOT,1,2016-05-02T10:44:23.000Z,2017-01-19T11:03:08.000Z,...,398729.12,137596.790000,38.906229,-77.014652,WASHINGTON,DC,20001.0,238344.0,6.0,"By BANUA, SIMOUN: 5/2/2016 12:48:15 PM\nthis t..."
4,-77.004008,38.835935,947829,S0031,Bulk Collection,SWMA- Solid Waste Management Admistration,DPW,1,2016-05-02T11:49:49.000Z,2016-05-12T14:27:19.000Z,...,399652.25,129792.780000,38.835928,-77.004005,WASHINGTON,DC,20032.0,66302.0,8.0,w riggans collected bulk on 5/12/16*closed by ...

## Exercise 11

The default head command shows us 5 rows. Try increasing the number of rows it shows us.

In [14]:
df.head(10)

,X,Y,OBJECTID,SERVICECODE,SERVICECODEDESCRIPTION,SERVICETYPECODEDESCRIPTION,ORGANIZATIONACRONYM,SERVICECALLCOUNT,ADDDATE,RESOLUTIONDATE,...,XCOORD,YCOORD,LATITUDE,LONGITUDE,CITY,STATE,ZIPCODE,MARADDRESSREPOSITORYID,WARD,DETAILS
0,-77.068472,38.959221,928367,EMNPV,Emergency No-Parking Verification,PEMA- Parking Enforcement Management Administr...,DPW,1,2016-01-04T16:45:21.000Z,2016-01-04T21:13:04.000Z,...,394065.60,143480.700000,38.959214,-77.068470,WASHINGTON,DC,20015.0,262895.0,3.0,NaN
1,-77.028858,38.903745,947826,S0276,Parking Meter Repair,Transportation Operations Administration,DDOT,1,2016-05-02T11:43:31.000Z,2016-05-03T01:38:10.000Z,...,397497.09,137320.600003,38.903738,-77.028856,WASHINGTON,DC,20005.0,812754.0,2.0,Need More Information
2,-77.019418,38.941567,947827,S0361,Sidewalk Repair,Toa-Street & Bridge Maintenance,DDOT,1,2016-05-02T11:47:49.000Z,NaN,...,398316.79,141518.950000,38.941560,-77.019416,WASHINGTON,DC,20011.0,247564.0,4.0,NaN
3,-77.014655,38.906236,947828,PRUNING,Tree Pruning,Urban Forrestry,DDOT,1,2016-05-02T10:44:23.000Z,2017-01-19T11:03:08.000Z,...,398729.12,137596.790000,38.906229,-77.014652,WASHINGTON,DC,20001.0,238344.0,6.0,"By BANUA, SIMOUN: 5/2/2016 12:48:15 PM\nthis t..."
4,-77.004008,38.835935,947829,S0031,Bulk Collection,SWMA- Solid Waste Management Admistration,DPW,1,2016-05-02T11:49:49.000Z,2016-05-12T14:27:19.000Z,...,399652.25,129792.780000,38.835928,-77.004005,WASHINGTON,DC,20032.0,66302.0,8.0,w riggans collected bulk on 5/12/16*closed by ...
5,-77.004008,38.835935,947830,S0031,Bulk Collection,SWMA- Solid Waste Management Admistration,DPW,1,2016-05-02T11:49:50.000Z,2016-05-12T14:26:24.000Z,...,399652.25,129792.780000,38.835928,-77.004005,WASHINGTON,DC,20032.0,66302.0,8.0,w riggans collected bulk on 5/12/16*closed by ...
6,-77.020134,38.914935,986620,S0261,Parking Enforcement,PEMA- Parking Enforcement Management Administr...,DPW,1,2016-03-16T08:10:25.000Z,2016-03-16T11:01:29.000Z,...,398254.07,138562.500000,38.914927,-77.020132,WASHINGTON,DC,20001.0,238452.0,6.0,NaN
7,-77.018788,38.915155,986621,S0441,Trash Collection - Missed,SWMA- Solid Waste Management Admistration,DPW,1,2016-03-16T08:12:34.000Z,2016-03-18T11:20:03.000Z,...,398370.81,138586.890000,38.915147,-77.018786,WASHINGTON,DC,20001.0,229894.0,1.0,COMPLETED BY 3/17/16 D STREET CLOSED BY NDAVALL
8,-77.018788,38.915155,986622,S0441,Trash Collection - Missed,SWMA- Solid Waste Management Admistration,DPW,1,2016-03-16T08:12:35.000Z,2016-03-18T11:22:49.000Z,...,398370.81,138586.890000,38.915147,-77.018786,WASHINGTON,DC,20001.0,229894.0,1.0,COMPLETED BY D STREET 3/17/16 CLOSED BY NDAVALL
9,-77.011544,38.915718,986623,S0441,Trash Collection - Missed,SWMA- Solid Waste Management Admistration,DPW,1,2016-03-16T08:10:29.000Z,2016-03-25T08:13:57.000Z,...,398999.01,138649.350000,38.915711,-77.011542,WASHINGTON,DC,20001.0,300722.0,5.0,COMPLETED BY L FERGUSON 3/17/16 CLOSED BY NDA...

This is sort of any annoying way to look at the data, in my opinion. I'm usually interested in looking at the list of columns and the kinds of values they have, so I usually transpose the data when I print it as a head.

In [15]:
df.head().T

,0,1,2,3,4
X,-77.0685,-77.0289,-77.0194,-77.0147,-77.004
Y,38.9592,38.9037,38.9416,38.9062,38.8359
OBJECTID,928367,947826,947827,947828,947829
SERVICECODE,EMNPV,S0276,S0361,PRUNING,S0031
SERVICECODEDESCRIPTION,Emergency No-Parking Verification,Parking Meter Repair,Sidewalk Repair,Tree Pruning,Bulk Collection
SERVICETYPECODEDESCRIPTION,PEMA- Parking Enforcement Management Administr...,Transportation Operations Administration,Toa-Street & Bridge Maintenance,Urban Forrestry,SWMA- Solid Waste Management Admistration
ORGANIZATIONACRONYM,DPW,DDOT,DDOT,DDOT,DPW
SERVICECALLCOUNT,1,1,1,1,1
ADDDATE,2016-01-04T16:45:21.000Z,2016-05-02T11:43:31.000Z,2016-05-02T11:47:49.000Z,2016-05-02T10:44:23.000Z,2016-05-02T11:49:49.000Z
RESOLUTIONDATE,2016-01-04T21:13:04.000Z,2016-05-03T01:38:10.000Z,NaN,2017-01-19T11:03:08.000Z,2016-05-12T14:27:19.000Z
SERVICEDUEDATE,2016-01-05T16:45:00.000Z,2016-05-09T11:43:00.000Z,2016-09-20T11:47:00.000Z,2017-05-31T10:44:00.000Z,2016-05-20T11:49:00.000Z
SERVICEORDERDATE,2016-01-04T16:45:21.000Z,2016-05-02T11:43:31.000Z,2016-05-02T11:47:49.000Z,2016-05-02T10:44:23.000Z,2016-05-02T11:49:49.000Z
INSPECTIONFLAG,N,N,N,N,N
INSPECTIONDATE,NaN,NaN,NaN,NaN,NaN
INSPECTORNAME,NaN,NaN,NaN,NaN,NaN
SERVICEORDERSTATUS,CLOSED,CLOSED,IN-PROGRESS,CLOSED,CLOSED
STATUS_CODE,CLOSED,CLOSED,OPEN,CLOSED,CLOSED
SERVICEREQUESTID,16-00353175,16-00485849,16-00485860,16-00485852,16-00485867
PRIORITY,STANDARD,STANDARD,STANDARD,STANDARD,STANDARD
STREETADDRESS,3611 JENIFER STREET NW,1200 - 1299 BLOCK OF L STREET NW,4120 5TH STREET NW,1219 NEW JERSEY AVENUE NW,135 WILMINGTON PLACE SE
XCOORD,394066,397497,398317,398729,399652
YCOORD,143481,137321,141519,137597,129793
LATITUDE,38.9592,38.9037,38.9416,38.9062,38.8359
LONGITUDE,-77.0685,-77.0289,-77.0194,-77.0147,-77.004
CITY,WASHINGTON,WASHINGTON,WASHINGTON,WASHINGTON,WASHINGTON
STATE,DC,DC,DC,DC,DC
ZIPCODE,20015,20005,20011,20001,20032
MARADDRESSREPOSITORYID,262895,812754,247564,238344,66302
WARD,3,2,4,6,8
DETAILS,NaN,Need More Information,NaN,"By BANUA, SIMOUN: 5/2/2016 12:48:15 PM\nthis t...",w riggans collected bulk on 5/12/16*closed by ...

Now you can get a sense of what your data looks like. What do you think some of these columns mean?

## Exercise 12

Think about some of the column names and values you have. What do you think these columns are?

We probably want even more information about our variables or columns, so let's learn more about them.

First, we can get a quick list of column names this way also.

In [16]:
df.columns

Index(['X', 'Y', 'OBJECTID', 'SERVICECODE', 'SERVICECODEDESCRIPTION',
       'SERVICETYPECODEDESCRIPTION', 'ORGANIZATIONACRONYM', 'SERVICECALLCOUNT',
       'ADDDATE', 'RESOLUTIONDATE', 'SERVICEDUEDATE', 'SERVICEORDERDATE',
       'INSPECTIONFLAG', 'INSPECTIONDATE', 'INSPECTORNAME',
       'SERVICEORDERSTATUS', 'STATUS_CODE', 'SERVICEREQUESTID', 'PRIORITY',
       'STREETADDRESS', 'XCOORD', 'YCOORD', 'LATITUDE', 'LONGITUDE', 'CITY',
       'STATE', 'ZIPCODE', 'MARADDRESSREPOSITORYID', 'WARD', 'DETAILS'],
      dtype='object')

The columns command provides us with a list of column names.

We can also use this command to find out how many columns we have by taking its length.

In [17]:
len(df.columns)

30

Note that this returns the same value as df.shape[1].

We can also get column data types.

In [18]:
df.dtypes

X                             float64
Y                             float64
OBJECTID                        int64
SERVICECODE                    object
SERVICECODEDESCRIPTION         object
SERVICETYPECODEDESCRIPTION     object
ORGANIZATIONACRONYM            object
SERVICECALLCOUNT                int64
ADDDATE                        object
RESOLUTIONDATE                 object
SERVICEDUEDATE                 object
SERVICEORDERDATE               object
INSPECTIONFLAG                 object
INSPECTIONDATE                 object
INSPECTORNAME                 float64
SERVICEORDERSTATUS             object
STATUS_CODE                    object
SERVICEREQUESTID               object
PRIORITY                       object
STREETADDRESS                  object
XCOORD                        float64
YCOORD                        float64
LATITUDE                      float64
LONGITUDE                     float64
CITY                           object
STATE                          object
ZIPCODE                       float64
MARADDRESSREPOSITORYID        float64
WARD                          float64
DETAILS                        object
dtype: object

We see three data types here. What does each mean? Why aren't there any "date" types?

## Exercise 13

We'd like to know even more about our data.

Use the describe function to learn more about your data. I like to transpose this, too. Try transposing it.

Do you notice any columns missing from the output? Why do you think they're missing?

You may notice some values are 'NaN'. What does that mean? How might we handle these values?

In [19]:
df.describe().T
#Because they are objects, I guess

,count,mean,std,min,25%,50%,75%,max
X,302985.0,-7.701344e+01,0.037492,-77.114209,-7.703655e+01,-7.701731e+01,-7.698978e+01,-7.690953e+01
Y,302985.0,3.891196e+01,0.031257,38.813455,3.889461e+01,3.890972e+01,3.893308e+01,3.899544e+01
OBJECTID,302985.0,1.335995e+06,102371.072802,928367.000000,1.264323e+06,1.340839e+06,1.417109e+06,1.566462e+06
SERVICECALLCOUNT,302985.0,1.000000e+00,0.000000,1.000000,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
INSPECTORNAME,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
XCOORD,302985.0,3.988348e+05,3251.499740,390097.460000,3.968295e+05,3.984992e+05,4.008872e+05,4.078484e+05
YCOORD,302985.0,1.382333e+05,3470.000502,127297.420000,1.363069e+05,1.379835e+05,1.405768e+05,1.475002e+05
LATITUDE,302985.0,3.891195e+01,0.031258,38.813448,3.889460e+01,3.890968e+01,3.893306e+01,3.899544e+01
LONGITUDE,302985.0,-7.701344e+01,0.037491,-77.114206,-7.703655e+01,-7.701731e+01,-7.698977e+01,-7.690976e+01
ZIPCODE,302983.0,2.002962e+04,867.804543,-1865.000000,2.000300e+04,2.001100e+04,2.001800e+04,7.073900e+04
MARADDRESSREPOSITORYID,294302.0,2.912035e+05,270115.221076,1.000000,6.951100e+04,2.405765e+05,2.946100e+05,9.141190e+05
WARD,300924.0,4.335025e+00,2.151176,1.000000,2.000000e+00,4.000000e+00,6.000000e+00,8.000000e+00

The describe function provides us a ton of great information about numeric variables, like integers and floats. But categorical variables, called "object" variables in Python, do not have means, mins, maxes, or standard deviations. So how might we analyze these?

One of the first steps is to take a look at the unique values of these columns. Let's start with the most interesting one: Service Code Description.

In [20]:
df['SERVICECODEDESCRIPTION'].unique()

array(['Emergency No-Parking Verification', 'Parking Meter Repair',
       'Sidewalk Repair', 'Tree Pruning', 'Bulk Collection',
       'Parking Enforcement', 'Trash Collection - Missed',
       'Sanitation Enforcement', 'Tree Inspection', 'Illegal Dumping',
       'Rodent Inspection and Treatment', 'Yard Waste - Missed',
       'Sidewalk Shoveling Enforcement Exemption', 'Emergency - Trees',
       'Sign Replacement', 'Alley Cleaning', 'Dead Animal Collection',
       'Abandoned Vehicle - On Private Property', 'DMV - Copy of Ticket',
       'Streetlight Repair Investigation', 'Recycling Cart Delivery',
       'Out of State Parking Violation (ROSA)',
       'DMV - Vehicle Registration Issues',
       'DMV - Drivers License/ID Issues', 'Pothole', 'Tree Planting',
       'Leaf Season Collection', 'Residential Snow Removal (ServeDC)',
       'Snow Removal Complaints for Sidewalks', 'Street Cleaning',
       'Street Repair', 'Supercan - Repair', 'Alleylight Repair',
       'Public Space Litter Can- Installation/Removal/Repair',
       'Snow/Ice Removal', 'Residential Parking Permit Violation',
       'Abandoned Vehicle - On Public Property',
       'DC Government Information', 'Trash Cart - Delivery',
       'Recycling Collection - Missed', 'Sign New Investigation',
       'Wire Down/Power Outage', 'Vacant Lot', 'Bicycle Issues',
       'How Is My Driving - Complaint', 'Signs Conflicting',
       'Snow/Ice Removal (Roadways AND Bridge walkways ONLY)',
       'DMV - Forms, Applications, and Manuals Request', 'Tree Removal',
       'Christmas Tree Removal-Seasonal', 'Sign Removal investigation',
       'TRU Report', 'DMV - Processing Center Manager',
       'FEMS - Community Events', 'Traffic Signal Maintanence',
       'Resident Parking Permit', 'Container Removal',
       'Supercan - Delivery', 'Bus/Rail Issues',
       'Homeless Services - Winter/Hypothermia Season',
       'Sign Missing Investigation', 'Snow Metro Bus Shelter/Stop',
       'Snow Ticket Reimbursement', 'DMV - Vehicle Title Issues',
       'DOEE - Engine Idling Tips', 'Abandoned Bicycle',
       'FEMS - Smoke Alarm Application', 'Traffic Calming',
       'Graffiti Removal', 'Utility Repair Investigation', 'Snow Towing',
       'Marking Installation', 'Public Space Litter Can-Collection',
       'DMV - Driver Record Issues', 'DOEE - Nuisance Odor Complaints',
       'Trash Cart Repair', 'DMV - Vehicle Insurance Lapse',
       'Insect Treatment', 'Alley Repair',
       'DMV - Online Processing Issues', 'Marking Removal',
       'DMV - Ticket Payment Dispute', 'Recycling Cart - Repair',
       'Illegal Poster', 'Curb and Gutter Repair', 'Marking Modification',
       'DOEE - Ban on Foam Food Containers',
       'DOEE - Construction – Erosion Runoff',
       'DMV - eTIMS Ticket Alert Services Issues',
       'How Is My Driving - Compliment', 'DMV - Refunds - Tickets',
       'Marking Maintenance', 'DMV - Hearings',
       'Traffic Safety Investigation', 'DOEE - Foam Ban Tips',
       'Recycling- Information Request',
       'DOEE - General Environmental Concerns',
       'DMV - Adjudication Supervisor', 'Safe Routes to School',
       'Roadway Repair', 'DMV - Driver and Vehicle Services Refund',
       'DMV - Vehicle Inspection Issues',
       'Curb and Gutter Repair Investigation', 'Light-Light Pole',
       'DMV - Drivers License/ID Reinstatement',
       'Emergency - Power Outage/Wires Down', 'Snow Other',
       'DMV - Offset Tracking', 'Roadway Marking Maintenance',
       '311Force Reported Issues', 'Alleylight Repair Investigation',
       'Signed Street Sweeping Missed', 'Insects', 'Traffic Signal Issue',
       'Grass and Weeds Mowing', 'Roadway Striping / Markings',
       'OUC NYE Test', 'Child Safety Seat Program',
       'School Crossing Guard', 'Streetcar',
       'Light-Tunnel/Underpass Light Repair',
       'General Environmental Concerns (DOEE)', 'Roadway Signs',
       'DPW Correspondence Tracking', 'DMV - Appeal',
       'Recycling - Commercial Only', 'Roadway Marking Modification',
       'Utility Repair Issue', 'DOEE - Bag Law Tips',
       'Light-Overhead Guide Sign Lighting Repair', 'Illegal Fireworks',
       'Emergency - Heating and Cooling', 'Emergency - Senior Assistance',
       'Emergency - Supplies', 'Report Invalid Address to GIS Dept',
       'FEMS - Fire Safety Education', 'Recycling - School Program',
       'School Transit Subsidy Program', 'Citation',
       'Emergency - Flooding', 'Roadway Marking Removal',
       'Bicycle Services', 'Ticket Ombudsman',
       'School Crossing Guard Program', 'DDS - Serious Medication Error',
       'SalesForce DC311 Application Request',
       'Hypothermia Shelter Information'], dtype=object)

We just did two new things right here: we called a column by using its column name, and we called its unique values.

There's another way to call columns from a Pandas DataFrame if you're feeling lazy and don't want to mess around with brackets.

In [21]:
df.SERVICECODEDESCRIPTION.unique()

array(['Emergency No-Parking Verification', 'Parking Meter Repair',
       'Sidewalk Repair', 'Tree Pruning', 'Bulk Collection',
       'Parking Enforcement', 'Trash Collection - Missed',
       'Sanitation Enforcement', 'Tree Inspection', 'Illegal Dumping',
       'Rodent Inspection and Treatment', 'Yard Waste - Missed',
       'Sidewalk Shoveling Enforcement Exemption', 'Emergency - Trees',
       'Sign Replacement', 'Alley Cleaning', 'Dead Animal Collection',
       'Abandoned Vehicle - On Private Property', 'DMV - Copy of Ticket',
       'Streetlight Repair Investigation', 'Recycling Cart Delivery',
       'Out of State Parking Violation (ROSA)',
       'DMV - Vehicle Registration Issues',
       'DMV - Drivers License/ID Issues', 'Pothole', 'Tree Planting',
       'Leaf Season Collection', 'Residential Snow Removal (ServeDC)',
       'Snow Removal Complaints for Sidewalks', 'Street Cleaning',
       'Street Repair', 'Supercan - Repair', 'Alleylight Repair',
       'Public Space Litter Can- Installation/Removal/Repair',
       'Snow/Ice Removal', 'Residential Parking Permit Violation',
       'Abandoned Vehicle - On Public Property',
       'DC Government Information', 'Trash Cart - Delivery',
       'Recycling Collection - Missed', 'Sign New Investigation',
       'Wire Down/Power Outage', 'Vacant Lot', 'Bicycle Issues',
       'How Is My Driving - Complaint', 'Signs Conflicting',
       'Snow/Ice Removal (Roadways AND Bridge walkways ONLY)',
       'DMV - Forms, Applications, and Manuals Request', 'Tree Removal',
       'Christmas Tree Removal-Seasonal', 'Sign Removal investigation',
       'TRU Report', 'DMV - Processing Center Manager',
       'FEMS - Community Events', 'Traffic Signal Maintanence',
       'Resident Parking Permit', 'Container Removal',
       'Supercan - Delivery', 'Bus/Rail Issues',
       'Homeless Services - Winter/Hypothermia Season',
       'Sign Missing Investigation', 'Snow Metro Bus Shelter/Stop',
       'Snow Ticket Reimbursement', 'DMV - Vehicle Title Issues',
       'DOEE - Engine Idling Tips', 'Abandoned Bicycle',
       'FEMS - Smoke Alarm Application', 'Traffic Calming',
       'Graffiti Removal', 'Utility Repair Investigation', 'Snow Towing',
       'Marking Installation', 'Public Space Litter Can-Collection',
       'DMV - Driver Record Issues', 'DOEE - Nuisance Odor Complaints',
       'Trash Cart Repair', 'DMV - Vehicle Insurance Lapse',
       'Insect Treatment', 'Alley Repair',
       'DMV - Online Processing Issues', 'Marking Removal',
       'DMV - Ticket Payment Dispute', 'Recycling Cart - Repair',
       'Illegal Poster', 'Curb and Gutter Repair', 'Marking Modification',
       'DOEE - Ban on Foam Food Containers',
       'DOEE - Construction – Erosion Runoff',
       'DMV - eTIMS Ticket Alert Services Issues',
       'How Is My Driving - Compliment', 'DMV - Refunds - Tickets',
       'Marking Maintenance', 'DMV - Hearings',
       'Traffic Safety Investigation', 'DOEE - Foam Ban Tips',
       'Recycling- Information Request',
       'DOEE - General Environmental Concerns',
       'DMV - Adjudication Supervisor', 'Safe Routes to School',
       'Roadway Repair', 'DMV - Driver and Vehicle Services Refund',
       'DMV - Vehicle Inspection Issues',
       'Curb and Gutter Repair Investigation', 'Light-Light Pole',
       'DMV - Drivers License/ID Reinstatement',
       'Emergency - Power Outage/Wires Down', 'Snow Other',
       'DMV - Offset Tracking', 'Roadway Marking Maintenance',
       '311Force Reported Issues', 'Alleylight Repair Investigation',
       'Signed Street Sweeping Missed', 'Insects', 'Traffic Signal Issue',
       'Grass and Weeds Mowing', 'Roadway Striping / Markings',
       'OUC NYE Test', 'Child Safety Seat Program',
       'School Crossing Guard', 'Streetcar',
       'Light-Tunnel/Underpass Light Repair',
       'General Environmental Concerns (DOEE)', 'Roadway Signs',
       'DPW Correspondence Tracking', 'DMV - Appeal',
       'Recycling - Commercial Only', 'Roadway Marking Modification',
       'Utility Repair Issue', 'DOEE - Bag Law Tips',
       'Light-Overhead Guide Sign Lighting Repair', 'Illegal Fireworks',
       'Emergency - Heating and Cooling', 'Emergency - Senior Assistance',
       'Emergency - Supplies', 'Report Invalid Address to GIS Dept',
       'FEMS - Fire Safety Education', 'Recycling - School Program',
       'School Transit Subsidy Program', 'Citation',
       'Emergency - Flooding', 'Roadway Marking Removal',
       'Bicycle Services', 'Ticket Ombudsman',
       'School Crossing Guard Program', 'DDS - Serious Medication Error',
       'SalesForce DC311 Application Request',
       'Hypothermia Shelter Information'], dtype=object)

## Exercise 14

We can figure out how many unique values we have by getting the length of this object. Try it.

In [22]:
len(Out[18])

30

We can also get value counts for each unique value of a categorical variable using value_counts.

In [23]:
df.SERVICECODEDESCRIPTION.value_counts()

Bulk Collection                                         45405
Parking Meter Repair                                    34077
Parking Enforcement                                     33733
Emergency No-Parking Verification                       12644
Streetlight Repair Investigation                        12344
Pothole                                                 11225
Trash Collection - Missed                                8159
Alley Cleaning                                           7285
Residential Parking Permit Violation                     6680
Sanitation Enforcement                                   6423
Sidewalk Shoveling Enforcement Exemption                 5777
Snow/Ice Removal                                         5648
Illegal Dumping                                          5542
Recycling Collection - Missed                            5431
Sidewalk Repair                                          5403
Street Cleaning                                          5386
Residential Snow Removal (ServeDC)                       5336
Graffiti Removal                                         4972
Abandoned Vehicle - On Public Property                   4667
Tree Pruning                                             4071
DMV - Drivers License/ID Issues                          3993
Tree Inspection                                          3867
Rodent Inspection and Treatment                          3531
Out of State Parking Violation (ROSA)                    2945
Snow/Ice Removal (Roadways AND Bridge walkways ONLY)     2858
Tree Planting                                            2673
Dead Animal Collection                                   2654
DMV - Vehicle Registration Issues                        2600
TRU Report                                               2500
Tree Removal                                             2404
                                                        ...
Light-Tunnel/Underpass Light Repair                        19
OUC NYE Test                                               17
Marking Removal                                            14
Hypothermia Shelter Information                            11
Child Safety Seat Program                                  10
Streetcar                                                   7
DOEE - Bag Law Tips                                         6
Recycling - Commercial Only                                 5
Snow Other                                                  5
Roadway Marking Removal                                     4
School Crossing Guard Program                               4
Recycling - School Program                                  3
Emergency - Senior Assistance                               3
Insects                                                     2
Report Invalid Address to GIS Dept                          2
DPW Correspondence Tracking                                 2
Emergency - Flooding                                        2
School Transit Subsidy Program                              1
Emergency - Supplies                                        1
Ticket Ombudsman                                            1
Light-Light Pole                                            1
DOEE - Foam Ban Tips                                        1
FEMS - Fire Safety Education                                1
Illegal Fireworks                                           1
Emergency - Heating and Cooling                             1
Citation                                                    1
SalesForce DC311 Application Request                        1
DDS - Serious Medication Error                              1
General Environmental Concerns (DOEE)                       1
Light-Overhead Guide Sign Lighting Repair                   1
Name: SERVICECODEDESCRIPTION, dtype: int64

## Exercise 15

What's the most common request? What does that request mean? Check out the District's online 311 portal at 311.dc.gov to learn more about the top service request.

https://311.dc.gov/

In [24]:
%%html
<ion-page class="show-page service-type-component">
    <ion-header>
      <ion-toolbar class="toolbar">
    <div class="toolbar-background"></div>
    
    <ion-buttons start="">
        <button class="bar-button bar-button-default"><span class="button-inner">
          <span primary="">Cancel</span>
        </span><ion-button-effect></ion-button-effect></button>
      </ion-buttons>
    <ion-buttons end="">
          <button class="bar-button bar-button-default"><span class="button-inner">
            <span primary="">Submit</span>
          </span><ion-button-effect></ion-button-effect></button>
        </ion-buttons>
    <div class="toolbar-content">
      
      
        <ion-title><div class="toolbar-title">
          Residential Bulk Collection
        </div></ion-title>
        
      
    </div>
  </ion-toolbar>
    </ion-header>

    <ion-content padding=""><scroll-content style="margin-top: 56px;">
      <ion-list>
        <!--template bindings={}--><div class="service-type-description">
          <div>
            <p>Servicing Agency</p>
            <h4>DPW</h4>
          </div>
          <div>
            <p>Service Resolution Estimate</p>
            <h4>14 Business days</h4>
          </div>
          <div>
            <p>Please use this service request type to schedule pick up of up to 7 bulk items, such as household furniture, appliances, water heaters, mattresses, bed frames and tree limbs. Prohibited Items include hazardous materials, construction debris and tires. These items should be disposed of at the Ft. Totten Transfer Station which is located at 4900 John F. McCormack Road, N.E.</p>     
          </div>
        </div>
      </ion-list>
    </scroll-content></ion-content>
  </ion-page>

You can use the markdown hyperlink convention to link a website. You can embed HTML with the HTML cell magic --CDL

## Exercise 16
Take a look at the data using some of the techniques including shape, head, and describe.

Recall that we saw that date variables are stored as object data types in Pandas Data Frames.
However, we CAN turn them in to datetime types using Pandas's nifty datetime commands.
Let's begin by converting the service order date into a new datetime column in our DataFrame called "request_date".

In [25]:
df['request_date'] = pd.to_datetime(df['SERVICEORDERDATE'])

With any datetime object, we can use dt to pull the particulare date time that we're interested in.
Here we use the value_counts function to look at the data by month.

In [26]:
df.request_date.dt.month.value_counts() #This is cool, I never use this when I should.

1     34542
8     29892
9     26935
6     26253
7     25881
5     24289
10    24236
3     23892
4     23725
2     21541
11    20990
12    20809
Name: request_date, dtype: int64

Notice that January is the month in which the city received the most service requests. However, the other top months for service requests are all summer months, and our winter months (December, November, February) are those with the least service requests. Does January seem to be an anomaly? Let's look closer.
The value_counts function returns to pieces of information: the values, which are the actual counts of rows or observations, and the index, which the values are grouped by. In this case, the index is the set of months and the values are the number of service requests each month. The value_counts function returns an output that is sorted by the values, but we can also sort by the index using the sort_index function.

In [27]:
df.request_date.dt.month.value_counts().sort_index()

1     34542
2     21541
3     23892
4     23725
5     24289
6     26253
7     25881
8     29892
9     26935
10    24236
11    20990
12    20809
Name: request_date, dtype: int64

It may be helpful to plot this output to help us visualize the number of service requests made throughout the year.

In [28]:

requests_per_month = df.request_date.dt.month.value_counts()
requests_per_month.sort_index().plot()

We can see that January does, indeed, look anomalous. After spiking in January, service requests are low throughout the winter months, increasing as we move into the warmer months and peaking in August, after which they dip down again as we return to winter.
Let's take a look at what's happening in January. We can focus in on January by selecting the subset of our service requests that came in January.

In [29]:
jan_requests = df[df.request_date.dt.month==1]
print(jan_requests.request_date.min())
print(jan_requests.request_date.max())

2016-01-01 00:30:30
2016-01-31 23:43:20

Here, we've fed Python a logical statement telling it to return values from df where the date-part month in the column 'request_date' is equal to 1 (or January).
# Exercise 4
To better understand how this works, try taking the command out of the square brackets and running it. What does it return?

In [30]:
df.request_date.dt.month==1

0          True
1         False
2         False
3         False
4         False
5         False
6         False
7         False
8         False
9         False
10        False
11        False
12        False
13         True
14        False
15        False
16        False
17        False
18        False
19        False
20        False
21        False
22        False
23         True
24        False
25        False
26        False
27        False
28        False
29        False
          ...
302955    False
302956    False
302957    False
302958    False
302959    False
302960    False
302961    False
302962    False
302963    False
302964    False
302965    False
302966    False
302967    False
302968    False
302969    False
302970    False
302971    False
302972    False
302973    False
302974    False
302975    False
302976    False
302977    False
302978    False
302979    False
302980    False
302981    False
302982    False
302983    False
302984    False
Name: request_date, dtype: bool

This returns a string of True and False statements. The 'True' values are the ones the DataFrame keeps, and the 'False' ones, it discards.
Now that we have the January data, let's look at what kinds of requests were being made in January.

## Exercise 17

Get value counts for the service code description from the subsample of January service requests. What where the most common requests?

The city received a TON of snow removal requests in January 2016, but received very few other requests. It seems that these requests for snow removal are driving the high number of requests in January.
If you were living in the District in January 2016, you'll remember this was the month that Snowzilla hit the city. This was a record-breaking snowstorm that dumped feet of snow on the city from January 22nd to January 23rd.
Let's take a look at the top request in January, Snow/Ice Removal.

In [31]:
jan_requests['SERVICECODEDESCRIPTION'].value_counts()

Snow/Ice Removal                                        5347
Residential Snow Removal (ServeDC)                      5278
Sidewalk Shoveling Enforcement Exemption                5266
Snow/Ice Removal (Roadways AND Bridge walkways ONLY)    2768
Bulk Collection                                         2352
Parking Enforcement                                     2079
Parking Meter Repair                                    1997
Snow Removal Complaints for Sidewalks                   1030
Streetlight Repair Investigation                         817
Emergency No-Parking Verification                        558
Pothole                                                  543
Trash Collection - Missed                                444
Sanitation Enforcement                                   372
Residential Parking Permit Violation                     357
Abandoned Vehicle - On Public Property                   324
Alley Cleaning                                           309
DMV - Drivers License/ID Issues                          290
Illegal Dumping                                          269
Recycling Collection - Missed                            239
DMV - Vehicle Registration Issues                        238
Street Cleaning                                          226
Alleylight Repair                                        210
Sidewalk Repair                                          207
TRU Report                                               169
Out of State Parking Violation (ROSA)                    167
Dead Animal Collection                                   146
Christmas Tree Removal-Seasonal                          133
Sign Replacement                                         131
Traffic Signal Maintanence                               127
Street Repair                                            124
                                                        ...
DOEE - Construction – Erosion Runoff                       6
Safe Routes to School                                      5
DOEE - Engine Idling Tips                                  5
DC Government Information                                  5
Marking Modification                                       4
Snow Other                                                 4
Illegal Poster                                             4
DMV - Driver and Vehicle Services Refund                   4
DOEE - Ban on Foam Food Containers                         4
DMV - Vehicle Inspection Issues                            4
Recycling- Information Request                             3
Curb and Gutter Repair Investigation                       2
DMV - eTIMS Ticket Alert Services Issues                   2
Insect Treatment                                           2
Emergency - Power Outage/Wires Down                        2
Signed Street Sweeping Missed                              2
Marking Removal                                            1
Traffic Safety Investigation                               1
Alleylight Repair Investigation                            1
Light-Light Pole                                           1
DMV - Adjudication Supervisor                              1
Roadway Marking Maintenance                                1
Light-Overhead Guide Sign Lighting Repair                  1
Roadway Striping / Markings                                1
DOEE - Foam Ban Tips                                       1
School Crossing Guard                                      1
OUC NYE Test                                               1
Grass and Weeds Mowing                                     1
DMV - Offset Tracking                                      1
How Is My Driving - Compliment                             1
Name: SERVICECODEDESCRIPTION, dtype: int64

## Exercise 18

Get the subsample of service requests for Snow/Ice Removal. Get the number of requests for each day in January 2016, then plot those requests so we can look at them over the course of the month.

In [32]:
snow_df = jan_requests[jan_requests['SERVICECODEDESCRIPTION']== "Snow/Ice Removal"]

In [33]:
requests_per_day = snow_df.request_date.dt.day.value_counts()
requests_per_day.sort_index().plot()

We can see that almost all of the requests for snow and ice removal came in the days following Snowzilla.
Now let's take a look at WHERE those requests were coming from. DC is organized into 8 wards. These wards are the largest political geographies in the District. Each ward has a representative on the District Council who is elected directly by the residents of that ward.

## Exercise 19

Get the number of requests for snow and ice removal from each of the wards in January 2016.

In [34]:
all_snow = df[df['SERVICECODEDESCRIPTION']== "Snow/Ice Removal"]
request_per_ward = all_snow.WARD.value_counts()
request_per_ward

7.0    1193
5.0     881
8.0     874
4.0     835
3.0     688
6.0     442
1.0     419
2.0     279
Name: WARD, dtype: int64

By far, the most requests for snow and ice removal came from Ward 7, while the fewest (almost a thousand fewer) came from Ward 2.
Now let's take a look at response times. Ward 7 had the most requests, but is that an indication that the city was slower to plot roads in Ward 7 than it was in other wards?

## Exercise 20
Create a new date column from the resolution date column in our DataFrame of requests for snow and ice removal in January.

In [35]:
df['RESOLUTIONDATE']= pd.to_datetime(df['RESOLUTIONDATE'])
df['ADDDATE']= pd.to_datetime(df['ADDDATE'])

Because the resolution date comes AFTER the service request, the resolution date will always be 'greater' than the request date. We can get the amount of time took the city to respond to each service request by taking the difference between the resolution date and the request date.

## Exercise 21

Subtract the request date from the resolution date and assign that to an object called "time_diff". Print time_diff.

In [36]:
time_diff = df['RESOLUTIONDATE']-df['ADDDATE']
time_diff

0          0 days 04:27:43
1          0 days 13:54:39
2                      NaT
3        262 days 00:18:45
4         10 days 02:37:30
5         10 days 02:36:34
6          0 days 02:51:04
7          2 days 03:07:29
8          2 days 03:10:14
9          9 days 00:03:28
10         2 days 00:12:12
11                     NaT
12       149 days 00:39:26
13         0 days 01:22:42
14         0 days 11:58:39
15         0 days 10:01:25
16        16 days 05:00:36
17         7 days 05:44:36
18         9 days 00:07:17
19         0 days 21:42:16
20         0 days 04:05:57
21         9 days 17:49:17
22         0 days 04:02:51
23        38 days 01:41:44
24         0 days 02:48:46
25         0 days 00:00:00
26         0 days 00:18:03
27         8 days 02:24:42
28       121 days 04:54:58
29         1 days 04:07:38
                ...
302955                 NaT
302956                 NaT
302957                 NaT
302958                 NaT
302959   215 days 23:17:52
302960   211 days 18:09:18
302961    46 days 19:02:21
302962                 NaT
302963   175 days 03:13:28
302964   152 days 21:24:42
302965   359 days 00:56:56
302966   222 days 00:27:17
302967                 NaT
302968                 NaT
302969                 NaT
302970   173 days 09:24:27
302971                 NaT
302972   246 days 02:33:18
302973   252 days 00:34:41
302974   134 days 03:34:06
302975                 NaT
302976   105 days 17:38:11
302977   332 days 06:19:59
302978                 NaT
302979                 NaT
302980   102 days 14:17:36
302981                 NaT
302982                 NaT
302983                 NaT
302984    61 days 19:19:21
dtype: timedelta64[ns]

Great! Now let's convert time_diff to the number of hours it took to respond using the astype function. This function can be used to change the data type of a column. The timedelta64 function lets us convert to the datetime part we're interested in.

In [37]:
df['response_time']= time_diff.astype('timedelta64[h]')

## Exercise 22
Create a new column in our DataFrame calls "response_time" that is the time difference between resolution date and request date in hours.

In [38]:
df['response_time']

0            4.0
1           13.0
2            NaN
3         6288.0
4          242.0
5          242.0
6            2.0
7           51.0
8           51.0
9          216.0
10          48.0
11           NaN
12        3576.0
13           1.0
14          11.0
15          10.0
16         389.0
17         173.0
18         216.0
19          21.0
20           4.0
21         233.0
22           4.0
23         913.0
24           2.0
25           0.0
26           0.0
27         194.0
28        2908.0
29          28.0
           ...
302955       NaN
302956       NaN
302957       NaN
302958       NaN
302959    5183.0
302960    5082.0
302961    1123.0
302962       NaN
302963    4203.0
302964    3669.0
302965    8616.0
302966    5328.0
302967       NaN
302968       NaN
302969       NaN
302970    4161.0
302971       NaN
302972    5906.0
302973    6048.0
302974    3219.0
302975       NaN
302976    2537.0
302977    7974.0
302978       NaN
302979       NaN
302980    2462.0
302981       NaN
302982       NaN
302983       NaN
302984    1483.0
Name: response_time, dtype: float64

Now that we have our response times, let's use the groupby function to get the average response time by ward.

In [39]:
df.groupby('WARD').response_time.mean()

WARD
1.0    353.708141
2.0    453.247920
3.0    416.287066
4.0    509.956321
5.0    508.200059
6.0    376.486354
7.0    545.118179
8.0    490.214803
Name: response_time, dtype: float64

This looks a lot like the output from the value_counts function. In fact, value_counts is a type of groupby function that simply returns counts for each of the unique values in a column.
The groupby function allows us to aggregate the data by the unique values of a column (or multiple columns) and return various statistics, including mean, median, minimum (min), maximum (max), counts, etc.
Again, we have two parts to the output: the index, in this case the ward, and the values, in this case the average hours it to the city to respond to a request for snow and ice removal. The groupby function returns the values sorted by the index. However, we can sort the values by the value using the sort_values function.

## Exercise 23
Get the average response times by ward again and sort the values by the average response time in ascending order (from highest to lowest). Which ward had the longest response times? Which had the lowest?

Now we know which wards made the mo

In [40]:
group = df.groupby('WARD').response_time.mean()
group.sort_values(ascending=False)

WARD
7.0    545.118179
4.0    509.956321
5.0    508.200059
8.0    490.214803
2.0    453.247920
3.0    416.287066
6.0    376.486354
1.0    353.708141
Name: response_time, dtype: float64

Now we know which wards made the most requests for snow and ice removal following the historic snowstorm in January 2016. Why do you think some wards received faster service than others? Do you think you could build a model predicting which requests would receive the fastest response?

In [84]:
#Worth a try
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y

In [85]:
import pandas as pd
import numpy as np
import matplotlib as plt
%matplotlib inline
import sklearn as sm

In [86]:
#I had to split the cells to squash the timeout errors.
df_09 = pd.read_csv('https://opendata.arcgis.com/datasets/7c9ac81c00c14f4ba8c96df107f45e9d_0.csv',
                   low_memory=False, parse_dates=[9])

In [87]:
df_10 = pd.read_csv('https://opendata.arcgis.com/datasets/ba150a4170bc484b8cc204be308fa70c_1.csv',
                   low_memory=False, parse_dates=[9])

In [88]:
df_11 = pd.read_csv('https://opendata.arcgis.com/datasets/310e9e84ad7f4af7a31e7115395d7b57_2.csv',
                   low_memory=False, parse_dates=[9])

In [89]:
df_12 = pd.read_csv('https://opendata.arcgis.com/datasets/65a81d0a91654b9692c08ca37809c3c3_3.csv',
                   low_memory=False, parse_dates=[9])

In [90]:
df_13 = pd.read_csv('https://opendata.arcgis.com/datasets/20dc3ba98d494e51bee18a42f8430824_4.csv',
                   low_memory=False, parse_dates=[9])

In [91]:
df_14 = pd.read_csv('https://opendata.arcgis.com/datasets/17cafb3ffab347409def7e85e14c56bd_5.csv',
                   low_memory=False, parse_dates=[9])

In [92]:
df_15 = pd.read_csv('https://opendata.arcgis.com/datasets/b93ec7fc97734265a2da7da341f1bba2_6.csv',
                   low_memory=False, parse_dates=[9])

In [93]:
df_16 = pd.read_csv('https://opendata.arcgis.com/datasets/0e4b7d3a83b94a178b3d1f015db901ee_7.csv',
                   low_memory=False, parse_dates=[9])

In [94]:
df_17 = pd.read_csv('https://opendata.arcgis.com/datasets/19905e2b0e1140ec9ce8437776feb595_8.csv',
                   low_memory=False, parse_dates=[9])

data = [df_09, df_10, df_11, df_12, df_13, df_14, df_15, df_16, df_17]

In [95]:
#I was annoyed at how many NaTs I was getting in my data, but I did the visualization
#and realized how little it really is.
nans= [(i.RESOLUTIONDATE.value_counts(dropna=False)[0]/i.shape[0],
        i.RESOLUTIONDATE.value_counts(dropna=False)[0], i.shape[0]) for i in data]
print(sum([i[1] for i in nans]))
nans

143442

[(0.0025905537308599713, 56, 21617),
 (0.009834437086092716, 297, 30200),
 (0.014785328404890531, 156, 10551),
 (0.13422458251473476, 34980, 260608),
 (0.065158775797073673, 15297, 234765),
 (0.068667065671428884, 22143, 322469),
 (0.078049473502619801, 23074, 295633),
 (0.061788537386339257, 18721, 302985),
 (0.12949627311547707, 28718, 221767)]

In [96]:
#Ok the easy part is done I guess. Time to get my timedeltas
big = pd.concat(data)
dx= big.shape[0]

In [97]:
big.to_csv('data/big.csv', encoding='utf-8')

In [98]:
big['ADDDATE'] = pd.to_datetime(big['ADDDATE'], errors='coerce')
big['ADDDATE'].value_counts(dropna=False);

In [99]:
big.dtypes;

In [100]:
big['DELTARES'] = big['RESOLUTIONDATE']-big['ADDDATE']
big['DELTARES'] = big['DELTARES'].astype('timedelta64[s]')
big = big.dropna(subset=['DELTARES'])

big.head();

In [101]:
def reduction_measure(big, dx):
    #Given a big dataset and the orignal len, return the difference and percent remaining.
    dy = big.shape[0]
    return [(dx-dy), (dy/dx)]
reduction_measure(big, dx);
#I managed to parse and compute 91.5% of the rows

In [102]:
model_vars= ['X', 'Y', 'WARD', 'SERVICECODEDESCRIPTION', 'DELTARES', 'ADDDATE']

In [103]:
#Now that I look, it appears that there is are 6 latlong vars.
latlongs = ['XCOORD', 'YCOORD', 'LATITUDE', 'LONGITUDE', 'X', 'Y']
big[latlongs].head().T;

In [104]:
#X and Y COORD aren't for me, but a quick fillna on X/Y might help.
big.X.fillna(big['LONGITUDE'])
big.Y.fillna(big['LATITUDE'])
new_dx = big.shape[0]
for i in model_vars:
    bigna= big.dropna(subset=[i])
    print(reduction_measure(bigna, new_dx))

[0, 1.0]
[0, 1.0]
[23356, 0.9850056078102319]
[0, 1.0]
[0, 1.0]
[0, 1.0]

Dropna on 'WARD' will cause my remaining dataset to shrink by 1.6%, but I know the District tracks ward. I'm going to elect to keep it.

In [105]:
for i in model_vars:
    #Dropna in all the variables I want to load into the model
    big= big.dropna(subset=[i])

In [106]:
big = big[model_vars]

In [107]:
#I don't really care about service codes that occur only a few times in the dataset, do I?
counts = pd.DataFrame(big.SERVICECODEDESCRIPTION.value_counts())
counts.shape[0];

In [108]:
#We can drop more than half the service codes without losing many observations.
hds = counts[counts['SERVICECODEDESCRIPTION'] > 150]
print("Remaining Code Descriptions:",hds.shape[0])
print("Dropped lines:", counts.SERVICECODEDESCRIPTION.sum()-hds.SERVICECODEDESCRIPTION.sum())
print("% lines remaining:", hds.SERVICECODEDESCRIPTION.sum()/counts.SERVICECODEDESCRIPTION.sum())

Remaining Code Descriptions: 145
Dropped lines: 4086
% lines remaining: 0.9973368841544608

In [109]:
heads = hds.index
heads.tolist();
#Now I can look at all the headers that remain...

In [110]:
#Looks like a bunch of these codes are not for actual services. Noisy data has to go.
print(len(heads))
heads = [i for i in heads if i[0:3]!="xxx"]
print(len(heads));

145
135

In [111]:
heads;

In [112]:
big= big[big.SERVICECODEDESCRIPTION.isin(heads)]

In [113]:
big.dtypes;

Well I've got my dataframe as set up as it's likely to ever be. Now what do I think will best answer the original question? "Do you think you could build a model predicting which requests would receive the fastest response?"

Well if I build a reasonably effective model then my coefficients will tell me something like "on average requests from WARD X get a X hour different response time compared to other WARD." Right?

And we want a model that tries to predict the future right? So I should start feeding in more data, then create a train/test split with the test data all in the future right?

In [114]:
from pandas.tseries.holiday import USFederalHolidayCalendar

In [115]:
#Now that I have that...let's get a dummy var to flag every day on or adjacent to a holiday
#Some of this is snipped from the Python Datascience Handbook, Jake VanderPlas
USFederalHolidayCalendar()
cal = USFederalHolidayCalendar()
holidays = cal.holidays('2009', '2017')

In [116]:
holidays= pd.to_datetime(holidays)
holidays= pd.Series(holidays)
holidays.dt.date;

In [117]:
big['HOLIDAY']= 0
big['HOLIDAY'][big['ADDDATE'].dt.date.isin(holidays.dt.date.add(pd.Timedelta(1, 'D')))]= 1
big['HOLIDAY'][big['ADDDATE'].dt.date.isin(holidays.dt.date.subtract(pd.Timedelta(1, 'D')))]= 1
big['HOLIDAY'][big['ADDDATE'].dt.date.isin(holidays.dt.date)]= 1
big.HOLIDAY.value_counts();

C:\Users\clandau\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\clandau\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\clandau\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [118]:
#NOAA has some summary weather data at Reagan
noaa_df = pd.read_csv('data/clim_data.csv')

In [119]:
#Let's see what we got
noaa_df.T;

In [120]:
noaa_df.columns;

In [121]:
noaa_core = ['DATE','PRCP','SNOW', 'SNWD', 'TMAX', 'TMIN']
noaa      = noaa_df[noaa_core]
print(noaa.shape[0])
noaa_all  = noaa.dropna()
print(noaa_all.shape[0])
noaa_all.dtypes;

3174
3172

In [122]:
noaa_all['DATE']= pd.to_datetime(noaa_all['DATE']);

C:\Users\clandau\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [123]:
#Only a couple rows drop due to NaN, I can proceed to assign daily climate data to my main data.
merg = big.copy()
print(merg.shape[0])
merg['DATEDAY']= merg['ADDDATE'].dt.date
noaa_all['DATE']= noaa_all['DATE'].dt.date
merg= pd.merge(merg, noaa_all, left_on='DATEDAY', right_on='DATE',
              how='left', sort=False)
print(merg.shape[0])
merg = merg.dropna()
print(merg.shape[0])

1523495

C:\Users\clandau\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

1523495
1518815

In [124]:
merg['ADDHOUR']= merg['ADDDATE'].dt.hour

In [125]:
merg.to_csv('data/merged_data.csv', encoding='utf-8')
#merg = pd.read_csv('data/merged_data.csv', encoding='latin1')

In [126]:
#merg.head(10000).to_csv('data/merged_data_head.csv')

Well I've fed in some data and now it's time for a train-test split, right? This should be pretty easy.

In [127]:
serv_dex = merg.copy() #New dataframe for feature engineering and train-test splitting.

In [128]:
serv_dex;

In [129]:
#More feature engineering, hopefully this one doesn't break my machine.
serviceList = list(set(serv_dex.SERVICECODEDESCRIPTION))
print(serviceList)

['Out of State Parking Violation (ROSA)', 'Recycling Cart Delivery', 'Alley Cleaning', 'Sign Replacement', 'DMV - Vehicle Insurance Lapse', 'Recycling Container Delivery', 'Street Cleaning', 'Supercan - Repair', 'FEMS - Fire Safety Education', 'Recycling Cart - Repair', 'Streetlight Repair', 'Illegal Posters', 'DC Government Information', 'Street Sweeping', 'Dead Animal Collection', 'Dead Animal Pickup', 'Abandoned Bicycle', 'Marking Maintenance', 'DCRA - Vacant Building', 'Trash Collection - Missed', 'Safe Routes to School', 'Public Space Litter Can-Collection', 'Yard Waste - Missed', 'Trash Container - Delivery', 'DCRA - Trash and Debris', 'Alleylight Repair', 'TRU Report', 'DMV - Adjudication Supervisor', 'Snow Metro Bus Shelter/Stop', 'Street Repair', 'Traffic Signal Issue', 'Sidewalk Repair', 'Alleylight Repair Investigation', 'Yard Waste- Missed', 'DMV - Vehicle Title Issues', 'Container Removal', 'Residential Snow Removal (ServeDC)', 'Sign Removal Investigation', 'DMV - Vehicle Registration Issues', 'DMV - Processing Center Manager', 'Rodent Inspection and Treatment', 'DMV - Hearings', 'Graffiti Removal - Paint Voucher Request', 'Sanitation Enforcement', 'FEMS - Smoke Alarm Application', 'Sidewalk Shoveling Enforcement Exemption', 'Wire Down / Power Outage', 'Insect Treatment', 'DMV - Forms, Applications, and Manuals Request', 'CONTAINER REMOVAL', 'Parking Meter Repair', 'Marking Modification', 'DOEE - Nuisance Odor Complaints', 'Tree Removal', 'Signed Street Sweeping Missed', 'Litter Can - Installation/Removal/Repair', 'Graffiti Removal', 'Streetlight Repair Investigation', 'Tree Pruning', 'Bus/Rail Issues', 'Trash Cart Repair', 'Trash Container Repair', 'Christmas Tree Removal - Seasonal', 'Roadway Signs', 'Tree Inspection', 'Emergency - Trees', 'Wire Down/Power Outage', 'Trash Cart - Delivery', 'FEMS - Community Events', 'Traffic Safety Investigation', 'Emergency No-Parking Verification', 'Pothole', 'Child Safety Seat Program', 'Snow/Ice Removal', 'Parking Meter Issues', 'Alleylight Investigation', 'Alley Repair', 'Abandoned Vehicle - On Private Property', 'Traffic Calming', 'Pedestrian Safety Program', 'Supercan - Delivery', 'Utility Repair Issue', 'Litter Can - Collection', 'Insects', 'Bulk Collection', 'Recycling Collection - Missed', 'DMV - Online Processing Issues', 'Snow Other', '311Force Reported Issues', 'Illegal Poster', 'DMV - eTIMS Ticket Alert Services Issues', 'Sign Removal investigation', 'Grass and Weeds Mowing', 'DMV - Ticket Payment Dispute', 'Eviction', 'Utility Repair Investigation', 'Sign Missing Investigation', 'CSR Reported Issues', 'DMV - Refunds - Tickets', 'Illegal Dumping', 'Resident Parking Permit', 'Bus Shelters', 'Grass & Weeds Mowing', 'Abandoned Vehicle - On Public Property', 'Snow/Ice Removal (Roadways AND Bridge walkways ONLY)', 'Snow Removal Complaints for Sidewalks', "How's My Driving - Complaint", 'Traffic Signal Maintenance', 'Traffic Calming Investigation', 'How Is My Driving - Complaint', 'DPW Correspondence Tracking', 'Traffic Signal Maintanence', 'Roadway Striping / Markings', 'Recycling Container -Repair', 'DMV - Drivers License/ID Issues', 'School Crossing Guard', 'DMV - Copy of Ticket', 'Leaf Season Collection', 'Residential Parking Permit Violation', 'Signs Conflicting', 'Curb and Gutter Repair', 'Bicycle Issues', 'Tree Planting', 'Vacant Lot', 'DMV - Driver and Vehicle Services Refund', 'Marking Installation', 'Public Space Litter Can- Installation/Removal/Repair', 'Sign New Investigation', 'Parking Meter Request', 'Leaf Collection', 'Recycling Cart -Repair', 'Christmas Tree Removal-Seasonal', 'DOEE - Construction – Erosion Runoff', 'Parking Enforcement', 'Rat Abatement']

In [130]:
#Ugly for-loop
for j in list(set(serv_dex.SERVICECODEDESCRIPTION)):
    serv_dex[j] = 0
    serv_dex[j][serv_dex.SERVICECODEDESCRIPTION == j]=1

C:\Users\clandau\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [131]:
#Almost forgot day-of-week.
serv_dex['DayOfWeek'] = serv_dex.ADDDATE.dt.dayofweek
days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] #Snipped from PDHB, Jake VanderPlas
for i in range(7):
    serv_dex[days[i]] = (serv_dex.ADDDATE.dt.dayofweek == i).astype(float)
serv_dex= serv_dex.set_index(['ADDDATE']);

In [132]:
serv_dex.shape[0]*serv_dex.shape[1]

238453955

In [133]:
#MultiIndex it on date and timestamp
serv_dex.index = pd.MultiIndex.from_arrays([serv_dex.index.date, serv_dex.index],
                                           names=['Date', 'Timestamp'])
serv_dex= serv_dex.sort_index()
heads = ['X', 'Y', 'WARD', 'DELTARES', 'HOLIDAY', 'PRCP', 'SNOW',
         'SNWD', 'TMAX', 'TMIN'] + days + list(set(serv_dex.SERVICECODEDESCRIPTION))
serv_dex = serv_dex[heads]

In [134]:
#Another ugly for-loop
wards = ["Ward_"+str(i) for i in range(1, 9)]
for i in range(8):
    serv_dex[wards[i]] = 0
    serv_dex[wards[i]][serv_dex.WARD == i+1]= 1

check= ['WARD']+wards
serv_dex[check].head()

C:\Users\clandau\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

                               WARD  Ward_1  Ward_2  Ward_3  Ward_4  Ward_5  \
Date       Timestamp
2009-01-01 2009-01-01 12:30:00    5       0       0       0       0       1
2009-01-02 2009-01-02 00:12:00    6       0       0       0       0       0
           2009-01-02 14:05:00    4       0       0       0       1       0
           2009-01-02 14:34:00    7       0       0       0       0       0
           2009-01-02 16:03:00    4       0       0       0       1       0

                                Ward_6  Ward_7  Ward_8
Date       Timestamp
2009-01-01 2009-01-01 12:30:00       0       0       0
2009-01-02 2009-01-02 00:12:00       1       0       0
           2009-01-02 14:05:00       0       0       0
           2009-01-02 14:34:00       0       1       0
           2009-01-02 16:03:00       0       0       0

In [135]:
heads= []
for x in serv_dex.columns:
    if x != 'WARD':
        heads.append(x)

In [136]:
serv_dex = serv_dex[heads]
serv_dex.columns

Index(['X', 'Y', 'DELTARES', 'HOLIDAY', 'PRCP', 'SNOW', 'SNWD', 'TMAX', 'TMIN',
       'Mon',
       ...
       'Parking Enforcement', 'Rat Abatement', 'Ward_1', 'Ward_2', 'Ward_3',
       'Ward_4', 'Ward_5', 'Ward_6', 'Ward_7', 'Ward_8'],
      dtype='object', length=159)

In [137]:
serv_dex.dtypes.value_counts()

int64      144
float64     15
dtype: int64

# Finally I have finished and can model my data

In [169]:
split = serv_dex.copy()
split

                                        X          Y     DELTARES  HOLIDAY  \
Date       Timestamp
2009-01-01 2009-01-01 12:30:00 -77.003162  38.916587  199677072.0        1
2009-01-02 2009-01-02 00:12:00 -77.004730  38.902523  193833767.0        1
           2009-01-02 14:05:00 -77.025375  38.972922  199584972.0        1
           2009-01-02 14:34:00 -76.935891  38.889514  181240511.0        1
           2009-01-02 16:03:00 -77.044852  38.992085  181235186.0        1
           2009-01-02 16:11:00 -77.004395  38.836166  181234720.0        1
2009-01-05 2009-01-05 08:46:00 -77.014802  38.955307  199344913.0        0
           2009-01-05 09:29:00 -77.073478  38.969984  199342333.0        0
           2009-01-05 12:06:00 -77.036502  38.918122  181191221.0        0
           2009-01-05 13:46:18 -77.038137  38.901594  199326895.0        0
           2009-01-05 14:41:00 -77.044908  38.899587  181181957.0        0
2009-01-06 2009-01-06 09:43:00 -76.982900  38.908392  199255093.0        0
           2009-01-06 14:37:00 -76.979397  38.884284  199237454.0        0
           2009-01-06 15:32:00 -77.069248  38.912683  181092585.0        0
           2009-01-06 15:57:00 -76.991536  38.876505  181091171.0        0
           2009-01-06 15:58:00 -77.007555  38.910944  180484670.0        0
           2009-01-06 20:37:16 -77.066293  38.911559  199215838.0        0
           2009-01-06 22:04:29 -77.034162  38.969043  180867953.0        0
2009-01-07 2009-01-07 18:01:00 -77.019462  38.947410  180284762.0        0
2009-01-08 2009-01-08 08:46:00 -77.027479  38.967543  180944398.0        0
           2009-01-08 09:04:00 -76.979000  38.924517  199084635.0        0
           2009-01-08 12:10:00 -77.022966  38.927234  180932237.0        0
           2009-01-08 14:15:00 -77.017102  38.960172  180924769.0        0
           2009-01-08 14:51:00 -77.031954  38.914102  180922635.0        0
           2009-01-08 15:42:00 -76.990198  38.923131  180919651.0        0
           2009-01-08 16:34:00 -77.021902  38.892086  180916565.0        0
2009-01-09 2009-01-09 06:36:00 -77.021166  38.967295  199007115.0        0
           2009-01-09 08:47:35 -77.068629  38.905083  180158954.0        0
           2009-01-09 09:12:00 -76.974529  38.902941  198997755.0        0
           2009-01-09 09:15:00 -76.965985  38.868401  198997575.0        0
...                                   ...        ...          ...      ...
2017-09-06 2017-09-06 19:59:56 -77.085103  38.945011     113592.0        0
           2017-09-06 20:01:43 -77.048435  38.933985      52885.0        0
           2017-09-06 20:03:13 -77.022752  38.910959      71445.0        0
           2017-09-06 20:12:44 -76.982987  38.842221      67284.0        0
           2017-09-06 20:13:42 -77.065891  38.949237      11094.0        0
           2017-09-06 20:19:22 -77.037836  38.926094       7000.0        0
           2017-09-06 20:29:15 -77.080083  38.957202      60543.0        0
           2017-09-06 20:41:09 -76.981780  38.897043     118018.0        0
           2017-09-06 20:41:26 -77.011904  38.951877      22588.0        0
           2017-09-06 20:45:51 -77.038283  38.900772      95287.0        0
           2017-09-06 20:50:19 -77.045206  38.913218       3169.0        0
           2017-09-06 20:52:25 -77.087441  38.908047      18526.0        0
           2017-09-06 21:04:13 -77.051631  38.900913     664197.0        0
           2017-09-06 21:04:31 -76.989044  38.894958     116016.0        0
           2017-09-06 21:05:30 -77.036041  38.950023     147476.0        0
           2017-09-06 21:09:17 -77.036428  38.942943     380041.0        0
           2017-09-06 21:25:20 -77.023785  38.980610     652064.0        0
           2017-09-06 21:25:35 -76.974397  38.866699       2978.0        0
           2017-09-06 21:25:53 -77.031438  38.972122      55043.0        0
           2017-09-06 21:40:45 -76.933179  38.887961     188242.0        0
           2017-09-06 21:45:36 -77.016071  38.956031     105151.0        0
           2017-09-06 21:54:32 -77.002725  38.958517       8499.0        0
           2017-09-06 22:08:05 -77.020133  38.911422      63352.0        0
           2017-09-06 22:35:12 -77.022667  38.909925      61728.0        0
           2017-09-06 22:38:05 -77.016843  38.946813      97802.0        0
           2017-09-06 23:06:20 -77.067478  38.970749     653824.0        0
           2017-09-06 23:08:21 -77.007781  38.896868     560418.0        0
           2017-09-06 23:10:27 -77.020405  38.910955      47875.0        0
           2017-09-06 23:22:22 -77.020715  38.910634      59498.0        0
           2017-09-06 23:27:36 -77.014537  38.919438     402685.0        0

                                PRCP  SNOW  SNWD  TMAX  TMIN  Mon   ...    \
Date       Timestamp                                                ...
2009-01-01 2009-01-01 12:30:00  0.00   0.0   0.0  34.0  23.0  0.0   ...
2009-01-02 2009-01-02 00:12:00  0.00   0.0   0.0  43.0  30.0  0.0   ...
           2009-01-02 14:05:00  0.00   0.0   0.0  43.0  30.0  0.0   ...
           2009-01-02 14:34:00  0.00   0.0   0.0  43.0  30.0  0.0   ...
           2009-01-02 16:03:00  0.00   0.0   0.0  43.0  30.0  0.0   ...
           2009-01-02 16:11:00  0.00   0.0   0.0  43.0  30.0  0.0   ...
2009-01-05 2009-01-05 08:46:00  0.00   0.0   0.0  51.0  37.0  1.0   ...
           2009-01-05 09:29:00  0.00   0.0   0.0  51.0  37.0  1.0   ...
           2009-01-05 12:06:00  0.00   0.0   0.0  51.0  37.0  1.0   ...
           2009-01-05 13:46:18  0.00   0.0   0.0  51.0  37.0  1.0   ...
           2009-01-05 14:41:00  0.00   0.0   0.0  51.0  37.0  1.0   ...
2009-01-06 2009-01-06 09:43:00  0.52   0.0   0.0  41.0  32.0  0.0   ...
           2009-01-06 14:37:00  0.52   0.0   0.0  41.0  32.0  0.0   ...
           2009-01-06 15:32:00  0.52   0.0   0.0  41.0  32.0  0.0   ...
           2009-01-06 15:57:00  0.52   0.0   0.0  41.0  32.0  0.0   ...
           2009-01-06 15:58:00  0.52   0.0   0.0  41.0  32.0  0.0   ...
           2009-01-06 20:37:16  0.52   0.0   0.0  41.0  32.0  0.0   ...
           2009-01-06 22:04:29  0.52   0.0   0.0  41.0  32.0  0.0   ...
2009-01-07 2009-01-07 18:01:00  1.26   0.0   0.0  42.0  33.0  0.0   ...
2009-01-08 2009-01-08 08:46:00  0.00   0.0   0.0  42.0  30.0  0.0   ...
           2009-01-08 09:04:00  0.00   0.0   0.0  42.0  30.0  0.0   ...
           2009-01-08 12:10:00  0.00   0.0   0.0  42.0  30.0  0.0   ...
           2009-01-08 14:15:00  0.00   0.0   0.0  42.0  30.0  0.0   ...
           2009-01-08 14:51:00  0.00   0.0   0.0  42.0  30.0  0.0   ...
           2009-01-08 15:42:00  0.00   0.0   0.0  42.0  30.0  0.0   ...
           2009-01-08 16:34:00  0.00   0.0   0.0  42.0  30.0  0.0   ...
2009-01-09 2009-01-09 06:36:00  0.00   0.0   0.0  39.0  27.0  0.0   ...
           2009-01-09 08:47:35  0.00   0.0   0.0  39.0  27.0  0.0   ...
           2009-01-09 09:12:00  0.00   0.0   0.0  39.0  27.0  0.0   ...
           2009-01-09 09:15:00  0.00   0.0   0.0  39.0  27.0  0.0   ...
...                              ...   ...   ...   ...   ...  ...   ...
2017-09-06 2017-09-06 19:59:56  0.55   0.0   0.0  72.0  61.0  0.0   ...
           2017-09-06 20:01:43  0.55   0.0   0.0  72.0  61.0  0.0   ...
           2017-09-06 20:03:13  0.55   0.0   0.0  72.0  61.0  0.0   ...
           2017-09-06 20:12:44  0.55   0.0   0.0  72.0  61.0  0.0   ...
           2017-09-06 20:13:42  0.55   0.0   0.0  72.0  61.0  0.0   ...
           2017-09-06 20:19:22  0.55   0.0   0.0  72.0  61.0  0.0   ...
           2017-09-06 20:29:15  0.55   0.0   0.0  72.0  61.0  0.0   ...
           2017-09-06 20:41:09  0.55   0.0   0.0  72.0  61.0  0.0   ...
           2017-09-06 20:41:26  0.55   0.0   0.0  72.0  61.0  0.0   ...
           2017-09-06 20:45:51  0.55   0.0   0.0  72.0  61.0  0.0   ...
           2017-09-06 20:50:19  0.55   0.0   0.0  72.0  61.0  0.0   ...
           2017-09-06 20:52:25  0.55   0.0   0.0  72.0  61.0  0.0   ...
           2017-09-06 21:04:13  0.55   0.0   0.0  72.0  61.0  0.0   ...
           2017-09-06 21:04:31  0.55   0.0   0.0  72.0  61.0  0.0   ...
           2017-09-06 21:05:30  0.55   0.0   0.0  72.0  61.0  0.0   ...
           2017-09-06 21:09:17  0.55   0.0   0.0  72.0  61.0  0.0   ...
           2017-09-06 21:25:20  0.55   0.0   0.0  72.0  61.0  0.0   ...
           2017-09-06 21:25:35  0.55   0.0   0.0  72.0  61.0  0.0   ...
           2017-09-06 21:25:53  0.55   0.0   0.0  72.0  61.0  0.0   ...
           2017-09-06 21:40:45  0.55   0.0   0.0  72.0  61.0  0.0   ...
           2017-09-06 21:45:36  0.55   0.0   0.0  72.0  61.0  0.0   ...
           2017-09-06 21:54:32  0.55   0.0   0.0  72.0  61.0  0.0   ...
           2017-09-06 22:08:05  0.55   0.0   0.0  72.0  61.0  0.0   ...
           2017-09-06 22:35:12  0.55   0.0   0.0  72.0  61.0  0.0   ...
           2017-09-06 22:38:05  0.55   0.0   0.0  72.0  61.0  0.0   ...
           2017-09-06 23:06:20  0.55   0.0   0.0  72.0  61.0  0.0   ...
           2017-09-06 23:08:21  0.55   0.0   0.0  72.0  61.0  0.0   ...
           2017-09-06 23:10:27  0.55   0.0   0.0  72.0  61.0  0.0   ...
           2017-09-06 23:22:22  0.55   0.0   0.0  72.0  61.0  0.0   ...
           2017-09-06 23:27:36  0.55   0.0   0.0  72.0  61.0  0.0   ...

                                Parking Enforcement  Rat Abatement  Ward_1  \
Date       Timestamp
2009-01-01 2009-01-01 12:30:00                    0              0       0
2009-01-02 2009-01-02 00:12:00                    0              0       0
           2009-01-02 14:05:00                    0              0       0
           2009-01-02 14:34:00                    0              0       0
           2009-01-02 16:03:00                    0              0       0
           2009-01-02 16:11:00                    0              0       0
2009-01-05 2009-01-05 08:46:00                    0              0       0
           2009-01-05 09:29:00                    0              0       0
           2009-01-05 12:06:00                    0              0       1
           2009-01-05 13:46:18                    0              0       0
           2009-01-05 14:41:00                    0              0       0
2009-01-06 2009-01-06 09:43:00                    0              0       0
           2009-01-06 14:37:00                    0              0       0
           2009-01-06 15:32:00                    0              0       0
           2009-01-06 15:57:00                    0              0       0
           2009-01-06 15:58:00                    0              0       0
           2009-01-06 20:37:16                    0              0       0
           2009-01-06 22:04:29                    0              0       0
2009-01-07 2009-01-07 18:01:00                    0              0       0
2009-01-08 2009-01-08 08:46:00                    0              0       0
           2009-01-08 09:04:00                    0              0       0
           2009-01-08 12:10:00                    0              0       1
           2009-01-08 14:15:00                    0              0       0
           2009-01-08 14:51:00                    0              0       0
           2009-01-08 15:42:00                    0              0       0
           2009-01-08 16:34:00                    0              0       0
2009-01-09 2009-01-09 06:36:00                    0              0       0
           2009-01-09 08:47:35                    0              0       0
           2009-01-09 09:12:00                    0              0       0
           2009-01-09 09:15:00                    0              0       0
...                                             ...            ...     ...
2017-09-06 2017-09-06 19:59:56                    0              0       0
           2017-09-06 20:01:43                    0              0       1
           2017-09-06 20:03:13                    0              0       0
           2017-09-06 20:12:44                    0              0       0
           2017-09-06 20:13:42                    1              0       0
           2017-09-06 20:19:22                    1              0       1
           2017-09-06 20:29:15                    0              0       0
           2017-09-06 20:41:09                    0              0       0
           2017-09-06 20:41:26                    0              0       0
           2017-09-06 20:45:51                    0              0       0
           2017-09-06 20:50:19                    0              0       0
           2017-09-06 20:52:25                    0              0       0
           2017-09-06 21:04:13                    0              0       0
           2017-09-06 21:04:31                    0              0       0
           2017-09-06 21:05:30                    0              0       0
           2017-09-06 21:09:17                    0              0       0
           2017-09-06 21:25:20                    0              0       0
           2017-09-06 21:25:35                    1              0       0
           2017-09-06 21:25:53                    0              0       0
           2017-09-06 21:40:45                    0              0       0
           2017-09-06 21:45:36                    0              0       0
           2017-09-06 21:54:32                    1              0       0
           2017-09-06 22:08:05                    0              0       0
           2017-09-06 22:35:12                    0              0       0
           2017-09-06 22:38:05                    0              0       0
           2017-09-06 23:06:20                    0              0       0
           2017-09-06 23:08:21                    0              0       0
           2017-09-06 23:10:27                    0              0       0
           2017-09-06 23:22:22                    0              0       0
           2017-09-06 23:27:36                    0              0       0

                                Ward_2  Ward_3  Ward_4  Ward_5  Ward_6  \
Date       Timestamp
2009-01-01 2009-01-01 12:30:00       0       0       0       1       0
2009-01-02 2009-01-02 00:12:00       0       0       0       0       1
           2009-01-02 14:05:00       0       0       1       0       0
           2009-01-02 14:34:00       0       0       0       0       0
           2009-01-02 16:03:00       0       0       1       0       0
           2009-01-02 16:11:00       0       0       0       0       0
2009-01-05 2009-01-05 08:46:00       0       0       1       0       0
           2009-01-05 09:29:00       0       1       0       0       0
           2009-01-05 12:06:00       0       0       0       0       0
           2009-01-05 13:46:18       1       0       0       0       0
           2009-01-05 14:41:00       1       0       0       0       0
2009-01-06 2009-01-06 09:43:00       0       0       0       1       0
           2009-01-06 14:37:00       0       0       0       0       1
           2009-01-06 15:32:00       1       0       0       0       0
           2009-01-06 15:57:00       0       0       0       0       1
           2009-01-06 15:58:00       0       0       0       1       0
           2009-01-06 20:37:16       1       0       0       0       0
           2009-01-06 22:04:29       0       0       1       0       0
2009-01-07 2009-01-07 18:01:00       0       0       1       0       0
2009-01-08 2009-01-08 08:46:00       0       0       1       0       0
           2009-01-08 09:04:00       0       0       0       1       0
           2009-01-08 12:10:00       0       0       0       0       0
           2009-01-08 14:15:00       0       0       1       0       0
           2009-01-08 14:51:00       1       0       0       0       0
           2009-01-08 15:42:00       0       0       0       1       0
           2009-01-08 16:34:00       1       0       0       0       0
2009-01-09 2009-01-09 06:36:00       0       0       1       0       0
           2009-01-09 08:47:35       1       0       0       0       0
           2009-01-09 09:12:00       0       0       0       1       0
           2009-01-09 09:15:00       0       0       0       0       0
...                                ...     ...     ...     ...     ...
2017-09-06 2017-09-06 19:59:56       0       1       0       0       0
           2017-09-06 20:01:43       0       0       0       0       0
           2017-09-06 20:03:13       0       0       0       0       1
           2017-09-06 20:12:44       0       0       0       0       0
           2017-09-06 20:13:42       0       1       0       0       0
           2017-09-06 20:19:22       0       0       0       0       0
           2017-09-06 20:29:15       0       1       0       0       0
           2017-09-06 20:41:09       0       0       0       0       1
           2017-09-06 20:41:26       0       0       1       0       0
           2017-09-06 20:45:51       1       0       0       0       0
           2017-09-06 20:50:19       1       0       0       0       0
           2017-09-06 20:52:25       0       1       0       0       0
           2017-09-06 21:04:13       1       0       0       0       0
           2017-09-06 21:04:31       0       0       0       0       1
           2017-09-06 21:05:30       0       0       1       0       0
           2017-09-06 21:09:17       0       0       1       0       0
           2017-09-06 21:25:20       0       0       1       0       0
           2017-09-06 21:25:35       0       0       0       0       0
           2017-09-06 21:25:53       0       0       1       0       0
           2017-09-06 21:40:45       0       0       0       0       0
           2017-09-06 21:45:36       0       0       1       0       0
           2017-09-06 21:54:32       0       0       1       0       0
           2017-09-06 22:08:05       0       0       0       0       1
           2017-09-06 22:35:12       0       0       0       0       1
           2017-09-06 22:38:05       0       0       1       0       0
           2017-09-06 23:06:20       0       0       1       0       0
           2017-09-06 23:08:21       0       0       0       0       1
           2017-09-06 23:10:27       0       0       0       0       1
           2017-09-06 23:22:22       0       0       0       0       1
           2017-09-06 23:27:36       0       0       0       1       0

                                Ward_7  Ward_8
Date       Timestamp
2009-01-01 2009-01-01 12:30:00       0       0
2009-01-02 2009-01-02 00:12:00       0       0
           2009-01-02 14:05:00       0       0
           2009-01-02 14:34:00       1       0
           2009-01-02 16:03:00       0       0
           2009-01-02 16:11:00       0       1
2009-01-05 2009-01-05 08:46:00       0       0
           2009-01-05 09:29:00       0       0
           2009-01-05 12:06:00       0       0
           2009-01-05 13:46:18       0       0
           2009-01-05 14:41:00       0       0
2009-01-06 2009-01-06 09:43:00       0       0
           2009-01-06 14:37:00       0       0
           2009-01-06 15:32:00       0       0
           2009-01-06 15:57:00       0       0
           2009-01-06 15:58:00       0       0
           2009-01-06 20:37:16       0       0
           2009-01-06 22:04:29       0       0
2009-01-07 2009-01-07 18:01:00       0       0
2009-01-08 2009-01-08 08:46:00       0       0
           2009-01-08 09:04:00       0       0
           2009-01-08 12:10:00       0       0
           2009-01-08 14:15:00       0       0
           2009-01-08 14:51:00       0       0
           2009-01-08 15:42:00       0       0
           2009-01-08 16:34:00       0       0
2009-01-09 2009-01-09 06:36:00       0       0
           2009-01-09 08:47:35       0       0
           2009-01-09 09:12:00       0       0
           2009-01-09 09:15:00       1       0
...                                ...     ...
2017-09-06 2017-09-06 19:59:56       0       0
           2017-09-06 20:01:43       0       0
           2017-09-06 20:03:13       0       0

In [170]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import Lasso
from sklearn.linear_model import LinearRegression
import matplotlib.dates as mdates
import sklearn.metrics as met

In [216]:
def subset_Modeler(split, service, serviceList):
    #I did this and the process ran 
    #for over an hour without terminating on my home PC...
    #So this convenience function can model subsets now.
    split_heads = split.columns
    split = split[split[service]==1]
    i = int(split.shape[0] * .8) #80-20 split
    print("Rows:", i)
    X_heads = []
    for x in split_heads:
        if x != 'DELTARES':
            X_heads.append(x)
    for x in serviceList:
        if x != service:
            X_heads.remove(x)
    y_heads = 'DELTARES'
    print(X_heads)
    print(y_heads)
    X = split[X_heads]
    y = np.array(split[y_heads])
    
    y_train = y[:i]
    X_train = X[:i]
    i += 1 #Ensure no overlap
    X_test = X[i:]
    y_test = y[i:]
    
    model = make_pipeline(PolynomialFeatures(3),
                         Lasso(alpha=.01))
    #print(X_train, y_train)
    model.fit(X_train, y_train)
    return model, [X_train, y_train, X_test, y_test]

In [214]:
list(enumerate(serviceList))

[(0, 'Out of State Parking Violation (ROSA)'),
 (1, 'Recycling Cart Delivery'),
 (2, 'Alley Cleaning'),
 (3, 'Sign Replacement'),
 (4, 'DMV - Vehicle Insurance Lapse'),
 (5, 'Recycling Container Delivery'),
 (6, 'Street Cleaning'),
 (7, 'Supercan - Repair'),
 (8, 'FEMS - Fire Safety Education'),
 (9, 'Recycling Cart - Repair'),
 (10, 'Streetlight Repair'),
 (11, 'Illegal Posters'),
 (12, 'DC Government Information'),
 (13, 'Street Sweeping'),
 (14, 'Dead Animal Collection'),
 (15, 'Dead Animal Pickup'),
 (16, 'Abandoned Bicycle'),
 (17, 'Marking Maintenance'),
 (18, 'DCRA - Vacant Building'),
 (19, 'Trash Collection - Missed'),
 (20, 'Safe Routes to School'),
 (21, 'Public Space Litter Can-Collection'),
 (22, 'Yard Waste - Missed'),
 (23, 'Trash Container - Delivery'),
 (24, 'DCRA - Trash and Debris'),
 (25, 'Alleylight Repair'),
 (26, 'TRU Report'),
 (27, 'DMV - Adjudication Supervisor'),
 (28, 'Snow Metro Bus Shelter/Stop'),
 (29, 'Street Repair'),
 (30, 'Traffic Signal Issue'),
 (31, 'Sidewalk Repair'),
 (32, 'Alleylight Repair Investigation'),
 (33, 'Yard Waste- Missed'),
 (34, 'DMV - Vehicle Title Issues'),
 (35, 'Container Removal'),
 (36, 'Residential Snow Removal (ServeDC)'),
 (37, 'Sign Removal Investigation'),
 (38, 'DMV - Vehicle Registration Issues'),
 (39, 'DMV - Processing Center Manager'),
 (40, 'Rodent Inspection and Treatment'),
 (41, 'DMV - Hearings'),
 (42, 'Graffiti Removal - Paint Voucher Request'),
 (43, 'Sanitation Enforcement'),
 (44, 'FEMS - Smoke Alarm Application'),
 (45, 'Sidewalk Shoveling Enforcement Exemption'),
 (46, 'Wire Down / Power Outage'),
 (47, 'Insect Treatment'),
 (48, 'DMV - Forms, Applications, and Manuals Request'),
 (49, 'CONTAINER REMOVAL'),
 (50, 'Parking Meter Repair'),
 (51, 'Marking Modification'),
 (52, 'DOEE - Nuisance Odor Complaints'),
 (53, 'Tree Removal'),
 (54, 'Signed Street Sweeping Missed'),
 (55, 'Litter Can - Installation/Removal/Repair'),
 (56, 'Graffiti Removal'),
 (57, 'Streetlight Repair Investigation'),
 (58, 'Tree Pruning'),
 (59, 'Bus/Rail Issues'),
 (60, 'Trash Cart Repair'),
 (61, 'Trash Container Repair'),
 (62, 'Christmas Tree Removal - Seasonal'),
 (63, 'Roadway Signs'),
 (64, 'Tree Inspection'),
 (65, 'Emergency - Trees'),
 (66, 'Wire Down/Power Outage'),
 (67, 'Trash Cart - Delivery'),
 (68, 'FEMS - Community Events'),
 (69, 'Traffic Safety Investigation'),
 (70, 'Emergency No-Parking Verification'),
 (71, 'Pothole'),
 (72, 'Child Safety Seat Program'),
 (73, 'Snow/Ice Removal'),
 (74, 'Parking Meter Issues'),
 (75, 'Alleylight Investigation'),
 (76, 'Alley Repair'),
 (77, 'Abandoned Vehicle - On Private Property'),
 (78, 'Traffic Calming'),
 (79, 'Pedestrian Safety Program'),
 (80, 'Supercan - Delivery'),
 (81, 'Utility Repair Issue'),
 (82, 'Litter Can - Collection'),
 (83, 'Insects'),
 (84, 'Bulk Collection'),
 (85, 'Recycling Collection - Missed'),
 (86, 'DMV - Online Processing Issues'),
 (87, 'Snow Other'),
 (88, '311Force Reported Issues'),
 (89, 'Illegal Poster'),
 (90, 'DMV - eTIMS Ticket Alert Services Issues'),
 (91, 'Sign Removal investigation'),
 (92, 'Grass and Weeds Mowing'),
 (93, 'DMV - Ticket Payment Dispute'),
 (94, 'Eviction'),
 (95, 'Utility Repair Investigation'),
 (96, 'Sign Missing Investigation'),
 (97, 'CSR Reported Issues'),
 (98, 'DMV - Refunds - Tickets'),
 (99, 'Illegal Dumping'),
 (100, 'Resident Parking Permit'),
 (101, 'Bus Shelters'),
 (102, 'Grass & Weeds Mowing'),
 (103, 'Abandoned Vehicle - On Public Property'),
 (104, 'Snow/Ice Removal (Roadways AND Bridge walkways ONLY)'),
 (105, 'Snow Removal Complaints for Sidewalks'),
 (106, "How's My Driving - Complaint"),
 (107, 'Traffic Signal Maintenance'),
 (108, 'Traffic Calming Investigation'),
 (109, 'How Is My Driving - Complaint'),
 (110, 'DPW Correspondence Tracking'),
 (111, 'Traffic Signal Maintanence'),
 (112, 'Roadway Striping / Markings'),
 (113, 'Recycling Container -Repair'),
 (114, 'DMV - Drivers License/ID Issues'),
 (115, 'School Crossing Guard'),
 (116, 'DMV - Copy of Ticket'),
 (117, 'Leaf Season Collection'),
 (118, 'Residential Parking Permit Violation'),
 (119, 'Signs Conflicting'),
 (120, 'Curb and Gutter Repair'),
 (121, 'Bicycle Issues'),
 (122, 'Tree Planting'),
 (123, 'Vacant Lot'),
 (124, 'DMV - Driver and Vehicle Services Refund'),
 (125, 'Marking Installation'),
 (126, 'Public Space Litter Can- Installation/Removal/Repair'),
 (127, 'Sign New Investigation'),
 (128, 'Parking Meter Request'),
 (129, 'Leaf Collection'),
 (130, 'Recycling Cart -Repair'),
 (131, 'Christmas Tree Removal-Seasonal'),
 (132, 'DOEE - Construction – Erosion Runoff'),
 (133, 'Parking Enforcement'),
 (134, 'Rat Abatement')]

In [218]:
#For maximum snark I will run this against rat abatement.
i = 134
print(serviceList[i])
fitted_Model, splitsList = subset_Modeler(split, serviceList[i], serviceList)

Rat Abatement
Rows: 6296
['X', 'Y', 'HOLIDAY', 'PRCP', 'SNOW', 'SNWD', 'TMAX', 'TMIN', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun', 'Rat Abatement', 'Ward_1', 'Ward_2', 'Ward_3', 'Ward_4', 'Ward_5', 'Ward_6', 'Ward_7', 'Ward_8']
DELTARES

C:\Users\clandau\AppData\Local\Continuum\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:484: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)

In [ ]:
splitsList[3]

In [219]:
yfit = fitted_Model.predict(splitsList[2])

In [220]:
met.explained_variance_score(splitsList[3], yfit)

-98.463780758002443

In [221]:
met.r2_score(splitsList[3], yfit)

-250.26318226120739